-- ===========================================================
-- SERGINHO MULTIMARCAS — script de configuração do banco de dados
--
-- IMPORTANTE: as duas lojas (Surubim e Limoeiro) usam a MESMA tabela.
-- O que diferencia o estoque de cada loja é só a coluna "cidade" —
-- não é preciso criar dois bancos nem duas tabelas.
--
-- COMO USAR (uma vez só):
-- 1. Crie um projeto grátis em https://supabase.com
-- 2. No menu lateral, abra "SQL Editor"
-- 3. Clique em "New query", cole TODO este arquivo, e clique em "Run"
-- 4. Pronto — a tabela é criada já com os 24 produtos de exemplo (12 por loja).
--
-- Depois disso você NUNCA MAIS precisa mexer em SQL. Todo o dia a dia
-- (adicionar, editar, remover produto de qualquer uma das lojas) é feito
-- pela tela em admin.html, escolhendo a loja num campo simples.
--
-- Depois de rodar este script, copie a "Project URL" e a chave
-- "anon public" (Project Settings → API) e cole em main.js.
-- ===========================================================

create table if not exists produtos (
  id          bigint generated by default as identity primary key,
  cidade      text not null,          -- "Surubim" ou "Limoeiro"
  categoria   text not null,
  nome        text not null,
  slug        text not null unique,
  foto        text,
  preco       numeric(10,2) not null default 0,
  marca       text not null default '',
  tamanhos    text not null default '',
  cores       text not null default '',
  destaque    boolean not null default false,
  descricao   text not null default '',
  ativo       boolean not null default true,
  criado_em   timestamptz not null default now()
);

alter table produtos enable row level security;

drop policy if exists "Leitura publica" on produtos;
create policy "Leitura publica" on produtos
  for select using (true);

drop policy if exists "Escrita autenticada" on produtos;
create policy "Escrita autenticada" on produtos
  for all to authenticated using (true) with check (true);

delete from produtos;

insert into produtos (cidade, categoria, nome, slug, foto, preco, marca, tamanhos, cores, destaque, descricao, ativo) values
  ('Surubim', 'Camisas', 'Camisa Social Slim Aramis', 'camisa-social-aramis-sb', NULL, 189.90, 'Aramis', 'P;M;G;GG', 'Branco;Azul', true, 'Tecido leve, corte slim, ideal pro dia a dia no trabalho.', true),
  ('Surubim', 'Camisas', 'Camisa Xadrez Flanelada', 'camisa-xadrez-flanelada-sb', NULL, 139.90, 'Ogochi', 'M;G;GG', 'Verde;Vermelho', false, 'Estampa xadrez, tecido macio, perfeita pra temporada de frio.', true),
  ('Surubim', 'Calças', 'Calça Social Alfaiataria', 'calca-social-alfaiataria-sb', NULL, 229.90, 'Aramis', '38;40;42;44', 'Preto;Cinza', true, 'Modelagem reta, caimento impecável para o dia a dia formal.', true),
  ('Surubim', 'Calças', 'Calça Jeans Skinny', 'calca-jeans-skinny-sb', NULL, 249.90, 'Diesel', '38;40;42', 'Azul', false, 'Jeans premium com elastano, ajuste moderno.', true),
  ('Surubim', 'Ternos & Blazers', 'Terno Slim Fit 2 Peças', 'terno-slim-fit-sb', NULL, 799.90, 'Aramis', '48;50;52', 'Azul Marinho;Preto', true, 'Corte slim, tecido nobre — pronto pra qualquer ocasião especial.', true),
  ('Surubim', 'Ternos & Blazers', 'Blazer Casual Textura', 'blazer-casual-textura-sb', NULL, 449.90, 'Ellus', 'M;G;GG', 'Bege;Cinza', false, 'Peça coringa pra elevar qualquer look sem parecer formal demais.', true),
  ('Surubim', 'Casacos & Jaquetas', 'Jaqueta Corta-Vento', 'jaqueta-corta-vento-sb', NULL, 279.90, 'Diesel', 'M;G;GG', 'Preto;Verde', false, 'Leve, resistente ao vento, ótima pra passeio ou viagem.', true),
  ('Surubim', 'Casacos & Jaquetas', 'Casaco em Camurça Sintética', 'casaco-camurca-sb', NULL, 459.90, 'Ellus', 'M;G', 'Marrom', true, 'Acabamento premium, forro quente, visual sofisticado.', true),
  ('Surubim', 'Infantil', 'Conjunto Infantil Camisa+Bermuda', 'conjunto-infantil-sb', NULL, 129.90, 'Republic P.', '4;6;8;10', 'Azul;Verde', false, 'Conjunto confortável para o dia a dia das crianças.', true),
  ('Surubim', 'Infantil', 'Camisa Polo Infantil', 'camisa-polo-infantil-sb', NULL, 79.90, 'Republic P.', '4;6;8;10;12', 'Branco;Azul', false, 'Algodão macio, ótimo caimento para o dia a dia escolar.', true),
  ('Surubim', 'Acessórios', 'Cinto de Couro Legítimo', 'cinto-couro-sb', NULL, 99.90, 'Aramis', 'Único', 'Preto;Marrom', false, 'Couro legítimo, fivela em metal reforçado.', true),
  ('Surubim', 'Acessórios', 'Relógio Casual Aço Escovado', 'relogio-casual-sb', NULL, 349.90, 'Diesel', 'Único', 'Prata;Preto', true, 'Design clean, pulseira em aço escovado, resistente à água.', true),

  ('Limoeiro', 'Camisas', 'Camisa Linho Manga Longa', 'camisa-linho-manga-longa-lm', NULL, 169.90, 'Ogochi', 'P;M;G;GG', 'Bege;Branco', true, 'Tecido respirável, visual leve e elegante.', true),
  ('Limoeiro', 'Camisas', 'Camisa Estampada Botânica', 'camisa-estampada-botanica-lm', NULL, 159.90, 'Ellus', 'M;G;GG', 'Verde', false, 'Estampa exclusiva, ótima pra ocasiões descontraídas.', true),
  ('Limoeiro', 'Calças', 'Calça Chino Slim', 'calca-chino-slim-lm', NULL, 199.90, 'Aramis', '38;40;42;44', 'Bege;Azul Marinho', true, 'Versátil, do casual ao semi-formal.', true),
  ('Limoeiro', 'Calças', 'Calça Jeans Reta Tradicional', 'calca-jeans-reta-lm', NULL, 219.90, 'Diesel', '40;42;44;46', 'Azul Escuro', false, 'Corte tradicional, conforto pro dia inteiro.', true),
  ('Limoeiro', 'Ternos & Blazers', 'Terno Risca de Giz Slim', 'terno-risca-de-giz-lm', NULL, 849.90, 'Aramis', '48;50;52;54', 'Cinza Chumbo', true, 'Estampa risca de giz, corte slim, para eventos formais.', true),
  ('Limoeiro', 'Ternos & Blazers', 'Blazer Estruturado Preto', 'blazer-estruturado-preto-lm', NULL, 479.90, 'Ellus', 'M;G;GG', 'Preto', false, 'Peça estruturada, ótima pra compor looks formais ou casuais.', true),
  ('Limoeiro', 'Casacos & Jaquetas', 'Jaqueta Jeans Trucker', 'jaqueta-jeans-trucker-lm', NULL, 299.90, 'Diesel', 'M;G;GG', 'Azul', true, 'Clássico atemporal, combina com quase tudo no guarda-roupa.', true),
  ('Limoeiro', 'Casacos & Jaquetas', 'Casaco Bomber Acolchoado', 'casaco-bomber-lm', NULL, 329.90, 'Ogochi', 'M;G', 'Preto;Verde Musgo', false, 'Quentinho, moderno e confortável pros dias mais frios.', true),
  ('Limoeiro', 'Infantil', 'Bermuda + Camiseta Infantil', 'bermuda-camiseta-infantil-lm', NULL, 109.90, 'Republic P.', '4;6;8;10', 'Cinza;Azul', false, 'Conjunto leve e confortável pra brincar o dia todo.', true),
  ('Limoeiro', 'Infantil', 'Jaqueta Infantil Corta-Vento', 'jaqueta-infantil-lm', NULL, 119.90, 'Republic P.', '6;8;10;12', 'Azul;Vermelho', false, 'Proteção contra o vento, leve pra levar na mochila.', true),
  ('Limoeiro', 'Acessórios', 'Carteira em Couro', 'carteira-couro-lm', NULL, 119.90, 'Aramis', 'Único', 'Preto;Marrom', false, 'Couro legítimo, vários compartimentos internos.', true),
  ('Limoeiro', 'Acessórios', 'Boné Aba Reta Premium', 'bone-aba-reta-lm', NULL, 89.90, 'Diesel', 'Único', 'Preto;Bege', true, 'Acabamento premium, ajuste confortável.', true);
